a = {'a' ,'b' ,'c', 'e'}
b = {'o', 't', 'e', 'c'}
c = {'h', 'o', 'e', 'w', 'q', 's'}
d = [3, 6, 7, 1, 7, 5, 7, 8, 9, 3, 0, 2]

print ("a U B")
print (a.union(b))
print (a | b)
print ("**1-************")
print ("a & B")
print (a.intersection(b))
print (a & b)
print ("**2-************")
print ("a \ b")
print (a.difference(b))
print (a - b)
print ("b \ a")
print (b - a)
print ("**3-************")
print ("a = U \ a")
print ("**4-************")
print ((a & b) | (b & c))
print ("**5-************")
a.add('z')
b.add('x')
print (a)
print (b)
print ("**6-************")
c.remove('h')
print (c)
print ("**7-************")
b.clear()
print (b)
print ("**8-************")
print ("convert list to set (want unique values, perform operations)")
g = set(d)
print (d)
print (g)
print (a | set(d))
print ("**9-************")
